In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
a.sum()


np.int64(15)

In [5]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [6]:
a.sum(axis=0) #axis=0 (rows) , Axis=1(columns)

array([4, 6])

In [7]:
a.sum(axis=1)

array([3, 7])

In [8]:
#broadcasting

a=np.array([5,7,3,1])
b=np.array([90,50,0,30])
c=a*b
c

array([450, 350,   0,  30])

In [9]:
a=np.array([1,2])
a*2

array([2, 4])

In [10]:
#more useful operatons.
a=np.array([1,2,3,4,5,6,7])
a.max()

np.int64(7)

In [11]:
a=np.array([0,1,2,3,4,5,6,7])
a.min()
a.sum()
a.mean()

np.float64(3.5)

In [12]:
a=np.array([0,1,2,3,4,5,6,7,8,9,10])
a.std()

np.float64(3.1622776601683795)

In [13]:
a=np.array([0,1,2,3,4,5,6,7])
a.prod()

np.int64(0)

In [14]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 
# and verify that last dimension has value 4

import numpy as np
arr =np.array([1,2,3,4,5],ndmin=6)
print(arr)
arr.shape

[[[[[[1 2 3 4 5]]]]]]


(1, 1, 1, 1, 1, 5)

In [15]:

#size of an numpy
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.size(array,axis=0))


3


In [16]:
#generating random numbers
import numpy as np
np.random.random((3,2))

array([[0.27085091, 0.37888156],
       [0.29178956, 0.77540341],
       [0.6808607 , 0.26011457]])

In [17]:
#get umique items
a=np.array([11,12,11,12,13,14,15,16,17,13,14,12,18,19,20,12,13,15])
np.unique(a,return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  1,  4,  5,  6,  7,  8, 12, 13, 14]))

In [18]:
#count the values
np.unique(a,return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([2, 4, 3, 2, 2, 1, 1, 1, 1, 1]))

In [19]:
#transpose the array

a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
#reverse an array
 
import numpy as np
# arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# rev=np.flip(arr)
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [35]:
#FLATTEN():Convert the 1D array

import numpy as next
arr=next.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])