In [29]:
import numpy as np
a=np.array([1,2,3,4])
a


array([1, 2, 3, 4])

In [30]:
import numpy as np
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
import numpy as np 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.arange(0,20,2) #(start,stop,step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
import numpy as np
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
#adding removing and shorting elements

a=np.array([1,2,3,4,5])
a
np.append(a,[6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
import numpy as np
a=np.array([1,2,3,4,5])
a
np.delete(a,[0,1])

array([3, 4, 5])

In [37]:
import numpy as np
a=np.array([1,2,3,4,5])


In [28]:
a.shape


(5,)

In [38]:
a.ndim

1

In [39]:
a.size

5

In [46]:
a=np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])