In [145]:
#one dimenstional array can be indexing ,slicing and iterated over,much like lists.


import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
arr[3]

np.int64(3)

In [147]:
arr[3]=100 #assigning to an index
arr

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [148]:
arr[3:8]

array([100,   4,   5,   6,   7])

In [149]:
arr[0:10:2] #slicing ,start:stop:step

array([0, 2, 4, 6, 8])

In [150]:
arr[0:10:2]=500 #replace with 500
arr

array([500,   1, 500, 100, 500,   5, 500,   7, 500,   9])

In [151]:
arr[::-1] #reverse an array

array([  9, 500,   7, 500,   5, 500, 100, 500,   1, 500])

In [152]:
for i in arr:
    print(i)

500
1
500
100
500
5
500
7
500
9


2D ARRAY

In [153]:
#multidimensional array INDEXING AND SLICING


import numpy as np
def nums(x,y):
    return 5*x+y

arr=np.fromfunction(nums,(5,5),dtype="int")
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [154]:
arr[2]

array([10, 11, 12, 13, 14])

In [155]:
arr[-1]

array([20, 21, 22, 23, 24])

In [156]:
arr[2,3] #slicing a particular value   #[row,column]

np.int64(13)

In [157]:
arr[1:4,4]#slicing some value from pirticular column

array([ 9, 14, 19])

In [158]:
arr[:,2]  #slicing all the values

array([ 2,  7, 12, 17, 22])

In [159]:
arr[3,2:5] #slicing some value from a particular row 

array([17, 18, 19])

In [160]:
arr[3,:] #slicing all values from a pirticular row

array([15, 16, 17, 18, 19])

#3D ARRAYS

In [161]:
dim=np.arange(45).reshape(3,3,5)   #(no_dim(or) Axis , no_rows , no_colm)
dim                              

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [162]:
dim.shape

(3, 3, 5)

In [163]:
dim[1,1,1] #indexing

np.int64(21)

In [164]:
dim[:,:,:] #slicing

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [165]:
dim[1:,:1,:1]

array([[[15]],

       [[30]]])

In [166]:
dim[1:2,:,:]

array([[[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [167]:
dim[2,0:2,0:3]

array([[30, 31, 32],
       [35, 36, 37]])

In [168]:
dim[:, :, 4] #particular column in all axis 

array([[ 4,  9, 14],
       [19, 24, 29],
       [34, 39, 44]])

In [169]:
for row in dim:
    print(row)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [170]:
for row in dim.flat:
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44


In [3]:
import pandas as pd
import numpy as np