In [50]:
import numpy as np
data= np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [51]:
data[-5:]

array([1, 2, 3, 4, 5])

In [52]:
data[0:2]

array([1, 2])

In [53]:
data[0:]

array([1, 2, 3, 4, 5])

In [54]:
data[-2:]

array([4, 5])

In [55]:
data[2:]

array([3, 4, 5])

In [56]:
# slicing and indexing
a=np.array([1,2,3,4,5,6,7,8,9,10])
array1=a[3:9]
array1

array([4, 5, 6, 7, 8, 9])

In [57]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
b=np.array([[7,8,9],[10,11,12]])
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [59]:
#concatenation
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [60]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])